name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 我们选择使用最新的ubuntu系统
    steps:
    - name: checkout
      uses: actions/checkout@master # 将代码拷贝到虚机中
      with:
          submodules: true

    - name: update submodule
      uses: srt32/git-actions@v0.0.3
      with:
        args: "git submodule update --remote"

    - name: commit and push
      uses: github-actions-x/commit@v2.1
      with:
        github-token: ${{ secrets.ACCESS_TOKEN }}
        push-branch: 'gh-pages'
        commit-message: 'publish'
        force-add: 'true'

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master 
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # 使用刚新建的secret
        BRANCH: gh-pages # 存放产物的分支名称
        FOLDER: dist # 存放build后产物的目录
        BUILD_SCRIPT: yarn install && yarn deploy # 执行的命令
